### ISSUE TITLE
Bug:  Minimap Button as a Data Broker issue

### ISSUE THREAD

**Issue by nancikennedy** [Thex-PiedDroit/KillThemAll#1]
On Retail, with the most recent version of KTA. mousing over the KTA broker:

1x KillThemAll/Settings/MinimapButton.lua:47: attempt to index global 'dataobj' (a nil value)
[string "@KillThemAll/Settings/MinimapButton.lua"]:47: in function `OnEnter'
[string "@Bazooka/Bazooka.lua"]:1582: in function `showTip'
[string "@Bazooka/Bazooka.lua"]:1387: in function <Bazooka/Bazooka.lua:1378>

Locals:
self = BazookaPlugin_KillThemAll {
 0 = <userdata>
 bzkPlugin = <table> {
 }
}
(*temporary) = nil
(*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined =[C]:-1
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined =[C]:-1
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:990
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined =[C]:-1
 NineSlice = Frame {
 }
 OnLoad = <function> defined @FrameXML/GameTooltip.lua:927
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 AddLineDataText = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:324
 SetSpellBookItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 textLeft1Font = "GameTooltipHeaderText"
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetArtifactPowerByID = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 SetAzeritePower = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLFGDungeonShortageReward = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetArtifactItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 StatusBar = GameTooltipStatusBar {
 }
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitAura = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <function> defined =[C]:-1
 SetConduit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetItem = <function> defined @FrameXML/GameTooltip.lua:986
 SetRecipeResultItem = <function> defined =[C]:-1
 SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetPvpTalent = <function> defined =[C]:-1
 SetExistingSocketGem = <function> defined =[C]:-1
 SetUnit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetTotem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 SetInfoBackdropStyle = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:338
 SetPetAction = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSlottedKeystone = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetItemInteractionItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLFGDungeonReward = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetUnit = <function> defined @FrameXML/GameTooltip.lua:994
 SetOwnedItemByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:4

**Comment by Thex-PiedDroit** [comment]
Thank you for pointing this out!

Fixed in e2e488996effcf5b2ec3b4108530a3b7340e7855
